extends Node

var rosemary = 0
var charcoal = 0
var ginseng = 0
var ginger = 0
var nettle = 0
var thistle = 0
var lavender = 0
var yarrow = 0
var comfrey = 0
var valerian = 0
var mugwort = 0
var blue_lotus = 0
var mandrake = 0
var honey = 0
var plantain = 0
var billberry = 0
var garlic = 0
var eyebright = 0
var bonemeal = 0
var bones = 0
var bonemarrow = 0
var lucky_clover = 0

var rosemary_seed = 0 #0
var ginseng_seed = 1
var ginger_seed = 1
var nettle_seed = 1
var thistle_seed = 0 #0
var lavender_seed = 0 #0
var yarrow_seed = 0 #0
var comfrey_seed = 1
var valerian_seed = 1
var mugwort_seed = 1
var blue_lotus_seed = 0 # 0
var mandrake_seed = 1
var plantain_seed = 1
var billberry_seed = 0 #0
var garlic_seed = 1
var eyebright_seed = 1

#POTIONS
var potionhealth = 1
var potionmana = 0
var potionhealthvial = 2
var potionhealthbig = 0
var potionregenhealth = 0
var potionbindingdecoc = 0
var potionlife = 0
var potionregenbig = 0
var purifelixir = 0
var potionfireres = 0
var potionrejuv = 0
var potionundyingelixir = 0
var potionsimplepoison = 0
var potionvenomvial = 0
var potionbleedthorn = 0
var potiontirelessbrew = 0
var potionstamina = 0
var potionpotentstamina = 0
var potionhunting = 0
var potionawareness = 0
var potiondreamwalker = 0
var potionmanabig = 0
var potionmanaalt = 0
var potionluck = 0
var potioninvis = 0
var potionvenompurge = 0
var potionplagueward = 0
var potionblossom = 0

#POTIONRECIPES
var recipepotionhealth = true
var recipepotionmana = true
var recipepotionhealthvial = true
var recipepotionhealthbig = true
var recipepotionregenhealth = true
var recipepotionbindingdecoc = true
var recipepotionlife = true
var recipepotionregenbig = true
var recipepurifelixir = true
var recipepotionfireres = true
var recipepotionrejuv = true
var recipepotionundyingelixir = true
var recipepotionsimplepoison = true
var recipepotionvenomvial = true
var recipepotionbleedthorn = true
var recipepotiontirelessbrew = true
var recipepotionstamina = true
var recipepotionpotentstamina = true
var recipepotionhunting = true
var recipepotionawareness = true
var recipepotiondreamwalker = true
var recipepotionmanabig = true
var recipepotionmanaalt = true
var recipepotionluck = true
var recipepotioninvis = true
var recipepotionvenompurge = true
var recipepotionplagueward = true
var recipepotionblossom = true

var bread = 1
var wine = 4
var cheapwine = 2
var finewine = 4
var rawmeat = 2
